---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-job
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: test
              image: busybox
              args: ["sleep", "180"]
          restartPolicy: OnFailure
