apiVersion: batch/v1
kind: CronJob
metadata:
  name: forbid-overlap-with-deadline
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sleep
              image: busybox
              command: ["sleep", "90"]
          restartPolicy: Never
