setup-clusters: create-clusters prepare-clusters

create-clusters:
    kind create cluster -n kind1
    kind create cluster -n kind2

delete-clusters:
    kind delete cluster -n kind1
    kind delete cluster -n kind2

prepare-clusters:
    helmfile apply -f core/helmfile.yaml -e kind1 --skip-diff-on-install
    helmfile apply -f core/helmfile.yaml -e kind2 --skip-diff-on-install
