apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - config.yaml

resources:
  - deployment.yaml
  - service.yaml
  - serviceMonitor.yaml
  - prometheusRule.yaml

commonLabels:
  app: redash-exporter
