apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: promstack
  name: redash-exporter
spec:
  groups:
    - name: redash-exporter.rules
      rules:
        - record: redash_queues
          expr: redash_queues_default
          labels:
            queue: default
        - record: redash_queues
          expr: redash_queues_emails
          labels:
            queue: emails
        - record: redash_queues
          expr: redash_queues_periodic
          labels:
            queue: periodic
        - record: redash_queues
          expr: redash_queues_queries
          labels:
            queue: queries
        - record: redash_queues
          expr: redash_queues_scheduled_queries
          labels:
            queue: scheduled_queries
        - record: redash_queues
          expr: redash_queues_schemas
          labels:
            queue: schemas
