[project]
name = "azure-mlflow-inspect"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "azure-ai-ml>=1.28.1",
    "azure-identity>=1.23.0",
    "azureml-mlflow>=1.60.0",
    "mlflow>=3.1.1",
]

[tool.ruff]
line-length = 120
