// Package petstore provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package petstore

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVy27bMBD8FWLbo2A7D/SgW9O0hS+F0SCnwgdaXMsMJJIhV24FQ/9eLCnHlmw0RtH0",
	"ogexj9mZIbmDwtbOGjQUIN9BKDZYy/i5QOKX89ahJ41xUSt+4i9Zuwohv5plsLa+lgQ5aEMfbiEDah2m",
	"XyzRQ5eBkTUO8kDZstR4CA7ktSk51m0s2UdfpXaEdfw4CesXpPey5f9AkpoY+t7jGnJ4Nz1MNu3Hmi6Q",
	"HlJg12Xg8bnRHhXkPxLE5Utdu3rCgrjwISXfgcJQeO1IWwM5OCSR+gptBG1QBLKep0LT1FxVbqWu5Kri",
	"NYdGMfgMgq3UUa/9UAxJm7WN82qKPC1iC+tRpBEggy36kPpfTWaTGWO0Do10GnK4mcwm19xM0iYinrpe",
	"RhvodIKPSgkpDP4UPAvZwRCsu+TAuUqh7IjEGga6s6rlgoU1hCbWls5Vuogp06fADfaGukCXNP8Q3ieP",
	"kvAI4Yjmg4DkG4yKBmdNSF69ns3eGuBDUxQYwrqpxAtb0VqhqWvp29coJlkG9gmLtOQ8lmu6c0hz1SW5",
	"KqS4d4Zq3Mf1JIiTXtZI6LnUWGE2kFbcty/FHmPvStrAfmdCbHhCaHZEzqu7vFuep38IJ7xOWBotCMmE",
	"nXCUQYlnjPwdqfGGk4I2ZYV97pC0r0gLpLs2jvpH1ub3wq73gvlY+78T95a+PS9DBrez21Nu2ULGkljb",
	"xqiRWF+0UZGnVSvm92fU2p87QyUenZIX2fdIiI0kYRBVYE1WKJpYQ72dLtkYzDdZ46Vwnhv07QFPfB23",
	"H5/9J83SpfOX7frbMLvcJS/X4r/axknifhuPD+7RuceJ6Ld7CzS+ghym2xtgNH3sGMLnLfqWNtqUQq5s",
	"Q6K1jRcLpDBwAXTL7ncAAAD//7ltc+flCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
