// Package petstore provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package petstore

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVTa8bNRT9K9aF5SgJ9InF7ChPoGzgCdoVysIZn8m4mrFd+86jUZT/jq49IZNJoW9B",
	"oZt8WPfj3HPOtU/U+CF4B8eJ6hOlpsOg888nsHyF6AMiW+RDa+QTH/QQelD9zaai1sdBM9VkHX/3QBXx",
	"MaD8xQGRzhU5PeAmj4w/HCyuwYmjdQeJDZ1n/zb2pR1jyD/uwqYDHaM+yv/Emscc+nVESzV9tb5Otp7G",
	"Wj+BfyuB53NFEe9HG2Go/r1A3P1V1+/foWEpfE2pT2SQmmgDW++opgBWpa+yTnEHldhHrKgiuHGQsvpZ",
	"217vexk1wBlBX1HyvZk1u0wlmKxrfR7YcibqKffwEarMQBU9I6YC4NVqIxB9gNPBloPVRlpp7jLgdZhU",
	"9InvB/jeGKWVwx9KRmF/nYFy1aglcGtKqBiikIbEr705SsHGO4bLtXUIvW1yyvpdkgYXP71AljL9Lbwf",
	"IjRjhnDOMs314zgiC5qCd6lY9dvN5nMDfNNBTXyoTieVxqYBDMwq+yuNw6Dj8VNEsz4k8YpItZM8EW19",
	"CuCtORfRenBeoFtNHvN5kSXoqAcwopRa6iwm2j5K36mU+EwMrLmjy3pSbnhHazWj6JOrft7difBwb7s3",
	"HSKUTcp5Nckj2BKcUa2PijubLrxWaj9ypquDNohJDfqo9lBjQjv2K7VgunCSlBam78it6ICP7MGv4DE6",
	"SUrWHXpMubds/wR+Ar8+Zo7+ke7to/LtRemYa/+XjP+vtq/o4W8kVwnxGVE12jnPqrXOZF2nSjAqIvkx",
	"Nlhuz48SKnTuj2r7+BFRL7fbrWBvg9EvWo+ZXp1m5QCTRDpxWa5hPp981RLMz3rAC+DgQ+i9AdWt7hMm",
	"eO9HxOMVX/6aw3FjXx6jCejy/bkDU16+fwnO9ETPAem+/6XNirzw1d5ViyG+gCun+Gy6cpZv1OJyl8S8",
	"BsWHY+yppvXzqzzZFHua+YvOu/OfAQAA//+7ir6OpAkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
