// Package petstore provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package petstore

// Defines values for PetStatus.
const (
	Available PetStatus = "available"
	Pending   PetStatus = "pending"
	Sold      PetStatus = "sold"
)

// Pet defines model for Pet.
type Pet struct {
	Id        *int64    `json:"id,omitempty"`
	Name      string    `json:"name"`
	PhotoUrls *[]string `json:"photoUrls,omitempty"`

	// Status pet status in the store.
	Status *PetStatus `json:"status,omitempty"`
}

// PetStatus pet status in the store.
type PetStatus string

// UpdatePetParams defines parameters for UpdatePet.
type UpdatePetParams struct {
	// Name Name of pet that needs to be updated
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Status Status of pet that needs to be updated
	Status *PetStatus `form:"status,omitempty" json:"status,omitempty"`
}

// AddPetJSONRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody = Pet
