// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package xtextmessage

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ja_JP": &dictionary{index: ja_JPIndex, data: ja_JPData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Hello, World!":       0,
	"Purchased %s at %s.": 1,
}

var en_USIndex = []uint32{ // 3 elements
	0x00000000, 0x0000000e, 0x00000028,
} // Size: 36 bytes

const en_USData string = "\x02Hello, World!\x02Purchased %[1]s at %[2]s."

var ja_JPIndex = []uint32{ // 3 elements
	0x00000000, 0x00000000, 0x00000000,
} // Size: 36 bytes

const ja_JPData string = ""

// Total table size 112 bytes (0KiB); checksum: C050B15D
