---
environments:
  kind1:
    kubeContext: kind-kind1
    values:
      - prometheus:
          enabled: true
          loadBalancerIP: "172.18.255.200"
        grafana:
          enabled: true
          loadBalancerIP: "172.18.255.201"
  kind2:
    kubeContext: kind-kind2
    values:
      - prometheus:
          enabled: true
          loadBalancerIP: "172.18.254.200"
        grafana:
          enabled: false
---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: prometheus
    condition: prometheus.enabled
    values:
      - server:
          service:
            loadBalancerIP: "{{ .Values.prometheus.loadBalancerIP }}"
            type: LoadBalancer
  - name: grafana
    chart: grafana/grafana
    namespace: grafana
    condition: grafana.enabled
    values:
      - service:
          loadBalancerIP: "{{ .Values.grafana.loadBalancerIP }}"
          type: LoadBalancer
        adminPassword: admin
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus | kind1
                type: prometheus
                url: http://172.18.255.200
              - name: Prometheus | kind2
                type: prometheus
                url: http://172.18.254.200
