---
environments:
  kind1:
    kubeContext: kind-kind1
    values:
      - ../environment-values/default.yaml
      - ../environment-values/ip.yaml
      - prometheus:
          enabled: true
        grafana:
          enabled: true
        loki:
          enabled: true
        promtail:
          enabled: true
        victoria-metrics:
          enabled: true
  kind2:
    kubeContext: kind-kind2
    values:
      - ../environment-values/default.yaml
      - ../environment-values/ip.yaml
      - prometheus:
          enabled: true
        promtail:
          enabled: true

---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: prometheus
    chart: prometheus-community/prometheus
    namespace: prometheus
    condition: prometheus.enabled
    values:
      - ../values/prometheus/{{ .Environment.Name }}.yaml.gotmpl
  - name: grafana
    chart: grafana/grafana
    namespace: grafana
    condition: grafana.enabled
    values:
      - ../values/grafana/{{ .Environment.Name }}.yaml.gotmpl
  - name: loki
    chart: grafana/loki
    namespace: loki
    condition: loki.enabled
    values:
      - ../values/loki/{{ .Environment.Name }}.yaml.gotmpl
  - name: promtail
    chart: grafana/promtail
    namespace: promtail
    condition: promtail.enabled
    values:
      - ../values/promtail/{{ .Environment.Name }}.yaml.gotmpl
