---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ include "metallb-config.fullname" . }}
spec:
  addresses:
    - {{ .Values.ipAddressPool.address }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ include "metallb-config.fullname" . }}
