apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-nginx
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: nginx-tmeplate
    files:
      - default.conf.template
