---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        # image: busybox:1.34.1
        image: busybox:1.34.0
        command: [sleep, "600"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command: [sleep, "60"]
