---
apiVersion: v1
kind: Namespace
metadata:
  name: image-pull-tester

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-pull-tester
  namespace: image-pull-tester
  labels:
    app: image-pull-tester
spec:
  selector:
    matchLabels:
      name: image-pull-tester
  template:
    metadata:
      labels:
        name: image-pull-tester
    spec:
      tolerations:
        - key: "taint-you-want-to-allow"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: app
          image: busybox:1.35.0
          imagePullPolicy: Always
          command:
            - sleep
            - "300"
      terminationGracePeriodSeconds: 1
