---
apiVersion: v1
kind: Namespace
metadata:
  name: unix-domain-socket

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: unix-domain-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: server
          image: local/unix-domain-socket:local
          volumeMounts:
            - mountPath: /app/socket
              name: socket
          args: ["socat", "unix-listen:/app/socket/test.sock", "stdout"]
        - name: client
          image: local/unix-domain-socket:local
          volumeMounts:
            - mountPath: /app/socket
              name: socket
          args:
            - sh
            - -c
            - |
              sleep 1
              while true; do
                date
                sleep 1
              done | socat stdin unix-connect:/app/socket/test.sock
      volumes:
        - name: socket
          emptyDir: {}
