multitenancyEnabled: true

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: minio.minio.svc:9000
      insecure: true
      access_key: sandbox
      secret_key: supersecret

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks
      trace_id_label_name: trace_id
      generate_native_histograms: native
      processor:
        service_graphs:
          dimensions:
            - service.name
            - service.namespace
        span_metrics:
          dimensions:
            - service.name
            - service.namespace
            - k8s.cluster.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name
            - k8s.pod.name
            - k8s.container.name
          dimension_mappings:
            - name: cluster
              source_labels: ["k8s.cluster"]
            - name: namespace
              source_labels: ["k8s.namespace.name"]
            - name: pod
              source_labels: ["k8s.pod.name"]
            - name: container
              source_labels: ["k8s.container.name"]
ingester:
  config:
    flush_all_on_shutdown: true
    replication_factor: 1 # dev:1, prod:1 or 3

metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
        - url: http://mimir-gateway.mimir.svc/api/v1/push
          send_exemplars: true

gateway:
  enabled: true

metaMonitoring:
  serviceMonitor:
    enabled: true

minio:
  enabled: false
