ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
querier:
  replicas: 1
query_frontend:
  replicas: 1
query_scheduler:
  replicas: 1
