[package]
name = "libinput"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = "0.7.0"
libc = "0.2.108"
nix = "0.23.0"
evdev = "0.11.1"
