# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json
---
environments:
  botkube1:
    kubeContext: kind-botkube1
    values:
        - envs/default.yaml
        - envs/botkube1.yaml
  botkube2:
    kubeContext: kind-botkube2
    values:
        - envs/default.yaml
        - envs/botkube2.yaml

---
repositories:
  - name: botkube
    url: https://charts.botkube.io

releases:
  - name: botkube
    namespace: botkube
    chart: botkube/botkube
    version: 1.6.0
    values:
      - values.yaml.gotmpl
