services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    environment:
      AZURITE_ACCOUNTS: "azurite:YXp1cml0ZQ==" # azurite:azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
