---
name: Auto approve merge

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Show Event
        run: echo "$event"
        env:
          labels: ${{ toJson(github.event) }}
      - name: Show actor
        run: echo "${{ github.actor }}"
