---
name: "Auto approve merge: Create PR"

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update
        run: date --iso-8601=seconds --utc > gha/auto_approve_and_merge/update.txt
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        id: create-pr
        with:
          branch: auto_approve_and_merge
          title: "[Automated] Auto approve and merge"
          labels: automated_pr
      - name: Run auto approve and merge workflow
        if: steps.create-pr.outputs.pull-request-operation == 'created' || steps.create-pr.outputs.pull-request-operation == 'updated'
        run: gh workflow run --ref auto_approve_and_merge auto_approve_and_merge.yaml
        env:
          GH_TOKEN: ${{ github.token }}

