---
name: Auto approve merge

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # [
      #   {
      #     "color": "a2eeef",
      #     "default": true,
      #     "description": "New feature or request",
      #     "id": 4359011016,
      #     "name": "enhancement",
      #     "node_id": "LA_kwDOHtbASc8AAAABA9E6yA",
      #     "url": "https://api.github.com/repos/buzztaiki/sandbox/labels/enhancement"
      #   }
      # ]
      - name: Show labels
        run: echo "$labels"
        env:
          labels: ${{ toJson(github.event.pull_request.labels) }}
      - name: Show actor
        run: echo "${{ github.actor }}"
