---
name: "Auto approve merge: Create PR"

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.AUTO_APPROVE_AND_MERGE_PR_SSH_PRIVATE_KEY }}
      - name: Update
        run: date --iso-8601=seconds --utc > gha/auto_approve_and_merge/update.txt
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        id: create-pr
        with:
          branch: auto_approve_and_merge
          title: "[Automated] Auto approve and merge"
          labels: automated_pr
