---
name: Auto approve merge

on:
  workflow_dispatch:
    inputs:
      pr-number: 
        description: 'PR number'
        required: true
        type: number

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Event
        run: echo "$event"
        env:
          event: ${{ toJson(github.event) }}
      - name: Show actor
        run: echo "${{ github.actor }}"
      - name: Show PR Info
        run: |
          gh pr view "${pr_number}"
          gh pr view
        env:
          GH_TOKEN: ${{ github.token }}
          pr_number: ${{ github.event.inputs.pr-number }}
